
package dev.sekousow.ebankingclient.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://sekousow.dev/ebanking")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @param account
     * @return
     *     returns dev.sekousow.ebankingclient.proxy.Account
     */
    @WebMethod(operationName = "CreateAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateAccount", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.CreateAccount")
    @ResponseWrapper(localName = "CreateAccountResponse", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.CreateAccountResponse")
    @Action(input = "http://sekousow.dev/ebanking/AccountService/CreateAccountRequest", output = "http://sekousow.dev/ebanking/AccountService/CreateAccountResponse")
    public Account createAccount(
        @WebParam(name = "account", targetNamespace = "http://sekousow.dev/ebanking")
        Account account);

    /**
     * 
     * @param amount
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "ConvertEuroToDirham")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertEuroToDirham", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.ConvertEuroToDirham")
    @ResponseWrapper(localName = "ConvertEuroToDirhamResponse", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.ConvertEuroToDirhamResponse")
    @Action(input = "http://sekousow.dev/ebanking/AccountService/ConvertEuroToDirhamRequest", output = "http://sekousow.dev/ebanking/AccountService/ConvertEuroToDirhamResponse")
    public Double convertEuroToDirham(
        @WebParam(name = "amount", targetNamespace = "")
        Double amount);

    /**
     * 
     * @return
     *     returns java.util.List<dev.sekousow.ebankingclient.proxy.Account>
     */
    @WebMethod(operationName = "GetAllAccounts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAllAccounts", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.GetAllAccounts")
    @ResponseWrapper(localName = "GetAllAccountsResponse", targetNamespace = "http://sekousow.dev/ebanking", className = "dev.sekousow.ebankingclient.proxy.GetAllAccountsResponse")
    @Action(input = "http://sekousow.dev/ebanking/AccountService/GetAllAccountsRequest", output = "http://sekousow.dev/ebanking/AccountService/GetAllAccountsResponse")
    public List<Account> getAllAccounts();

}
