
package dev.sekousow.ebankingclient.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BankAccountService", targetNamespace = "http://sekousow.dev/ebanking", wsdlLocation = "http://localhost:8282/ws/ebanking?wsdl")
public class BankAccountService
    extends Service
{

    private static final URL BANKACCOUNTSERVICE_WSDL_LOCATION;
    private static final WebServiceException BANKACCOUNTSERVICE_EXCEPTION;
    private static final QName BANKACCOUNTSERVICE_QNAME = new QName("http://sekousow.dev/ebanking", "BankAccountService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/ws/ebanking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKACCOUNTSERVICE_WSDL_LOCATION = url;
        BANKACCOUNTSERVICE_EXCEPTION = e;
    }

    public BankAccountService() {
        super(__getWsdlLocation(), BANKACCOUNTSERVICE_QNAME);
    }

    public BankAccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKACCOUNTSERVICE_QNAME, features);
    }

    public BankAccountService(URL wsdlLocation) {
        super(wsdlLocation, BANKACCOUNTSERVICE_QNAME);
    }

    public BankAccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKACCOUNTSERVICE_QNAME, features);
    }

    public BankAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort() {
        return super.getPort(new QName("http://sekousow.dev/ebanking", "AccountServicePort"), AccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sekousow.dev/ebanking", "AccountServicePort"), AccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKACCOUNTSERVICE_EXCEPTION!= null) {
            throw BANKACCOUNTSERVICE_EXCEPTION;
        }
        return BANKACCOUNTSERVICE_WSDL_LOCATION;
    }

}
